### ISSUE TITLE
Error with no clear path to resolve

### ISSUE THREAD

**Issue by tylersparks** [quentinms/GMR-client#1]
Pretty sure I did everything correctly, its a nice basic little app.

Error message is:

> Invalid date remaining

on the game screen.  It pulls the list of games successfully but I cannot upload/download.
![screen shot 2016-01-29 at 5 09 49 pm](https://cloud.githubusercontent.com/assets/13127469/12691642/2297790a-c6ab-11e5-88ba-39ecf9c4c507.png)
Platform is OSX 10.11
Thanks!

**Comment by quentinms** [comment]
Congrats on being issue #1!

I've never encountered this issue. Could you please open up the inspector (`⌘+⌥+I`), reload ((`⌘+R`) and tell me if you see any error in the console? Even better would be to send me the json that is received from GiantMultiplayerRobot.
If you need more info on how to accomplish this, please let me know :)

Thanks for the feedback!

**Comment by tylersparks** [comment]
Thanks for following up! The error is gone now and I cannot seem to reproduce it. I created a new game and it did not have the issue.

I realize now after using the game client that the "Invalid date remaining" error was unrelated, and just because the game did not have a turn timer.  Adding a check for that string and displaying the ∞ symbol instead might be a good outcome.  I am a bit busy right now but could add it in a pull request later if you would like.

Thanks! With the new game it seems to be working well!

**Comment by quentinms** [comment]
Oh, that makes sense. Didn't though about a game with no timer.
A PR would be great, I've got quite a lot of work this week.

If it helps, remaining time is computed in [index.js#L104](https://github.com/quentinms/GMR-client/blob/master/app/js/index.js#L104) (using moment.js; catching the error and returning ∞ instead should work) and displayed in [index.html#L66](https://github.com/quentinms/GMR-client/blob/master/app/index.html#L66)

Thanks a lot!
