### ISSUE TITLE
Save upload fails

### ISSUE THREAD

**Issue by igorrafael** [quentinms/GMR-client#3]
It seems that the program attempts to upload a directory. I worked around it by replacing [this line](https://github.com/quentinms/GMR-client/blob/master/app/gmr.js#L118) with the one below:

```
return fs.createReadStream(this.saveFile+'(GMR) Play this one!.Civ5Save')
```

The upload completed after this but I believe that this is not a good solution.

**Comment by quentinms** [comment]
We're already adding `'(GMR) Play this one!.Civ5Save'` at the end of the save file when we're asking for the folder ([changeSaveFile](https://github.com/quentinms/GMR-client/blob/master/app/js/index.js#L190)) in the settings tab so your workaround shouldn't be necessary.

Can you check the value in the `Settings` panel? What OS are you using?

**Comment by igorrafael** [comment]
My bad, I edited the config file directly and didn't notice the field was `saveFile` and not `save folder` like the settings menu. I also tested now and found out that downloads were also not completing. Maybe a validation that the path is a file and not a folder would make sense but that's a minor issue which will probably be solved by the "Watch folder for save changes" TODO.
